"""
Defines the graphical user interface (GUI) for the MediaFinder Desktop application
using PySimpleGUI. This module sets up the layout and controls for interacting with
the application, including fetching metadata, checking streaming availability, and
managing local media files. The GUI design focuses on simplicity and user-friendly
interaction to enhance the user experience.
"""
# app_gui.py
import PySimpleGUI as sg

def create_window():
    """
    Create the main application window and return it.
    """
    layout = [
        [sg.Text("MediaFinder Desktop")],
        [sg.Button("Fetch Metadata"), sg.Button("Check Availability"), sg.Button("Delete File")],
    ]
    return sg.Window("MediaFinder Desktop", layout)

def main():
    """
    The main function of the application.

    This function creates a window and handles the events generated by the user interface.
    It listens for events such as button clicks and prints a message to the console based on
    the event.
    The function continues to run until the window is closed by the user.
    """
    window = create_window()  # Define window by calling the create_window function

    while True:  # Event loop
        event, _ = window.read()  # Read events and values from the window
        if event == sg.WINDOW_CLOSED:  # If user closes window
            break
        if event == "Fetch Metadata":
            print("Fetch Metadata clicked")
        elif event == "Check Availability":
            print("Check Availability clicked")
        elif event == "Delete File":
            print("Delete File clicked")

    window.close()  # Close the window upon exiting the loop

if __name__ == "__main__":
    main()
